# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            James Wright
tagline:          'iOS Developer Notebook'
description:      'A collection of "that thing I showed you"''s, some "ohh yeah, I remember that"''s along with a few "hm, forgot about that bookmark"''s'
url:              http://james919.github.io
baseurl:          /

author:
  name:           'James Wright'
  url:            http://www.homestarrunner.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/james919/james919.github.io
