# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dev Notes
tagline:          'iOS Developer Notebook by James Wright'
description:      'A collection of odds and ends related to iOS development (mostly).'
url:              http://james919.github.io
baseurl:          /

author:
  name:           'James Wright'
  url:            http://www.homestarrunner.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/james919/james919.github.io
